### ISSUE TITLE
CH3: Adding custom help pages code doesn't work

### ISSUE THREAD

**Issue by gillaraz** [PacktPublishing/WordPress-Plugin-Development-Cookbook-Third-Edition#3]
Hi, I'm studying the book and get into CH3: Adding custom help pages. The code ch2-page-header-output-v8.php doesn't show the custom help page as it should be same in the book.

Currently, I use Wordpress Version 6.6.1 on local.

**Comment by ylefebvre** [comment]
Hello. Are you running your own version of the ch2-page-header-output-v8.php or did you download the one from this repository? I just downloaded a fresh copy of the file and placed it on a test site also using version WordPress 6.6.1. When I go to the Settings > My Google Analytics section of the admin, I see a little help tab appear in the top-right of the screen.

![image](https://github.com/user-attachments/assets/ec517ffb-7e20-4460-a24f-18768a322360)

If I click on that Help tab, I see exactly what is described in Chapter 3 in that recipe.

![image](https://github.com/user-attachments/assets/6a1974cf-ce93-4cd7-9d66-9587d0b8a6d5)

Please let me know if this helps.

**Comment by gillaraz** [comment]
Thanks so much, problem solved. It's my mistake not clicking on help tab to see the result.

**Comment by ylefebvre** [comment]
Glad to hear that's all it was. Enjoy the rest of the book and feel free to come back and ask more questions!
